### ISSUE TITLE
商业-倒货 的相关内容好像有问题

### ISSUE THREAD

**Issue by Madin-David** [qedsd/TheGuideToTheNewEden#10]
卖出价格 - 买单实际数量的相应价格
价格与买单价格对不上
![image](https://github.com/qedsd/TheGuideToTheNewEden/assets/93019806/53483bee-3cfb-43e4-9cdb-d74aea39672d)
如上 卖出价格 19 900 000 但实际上目的市场没有买单

**Comment by qedsd** [comment]
因为市场上没有买单导致的，软件默认当选择的价格方式没法满足时（如市场上没有卖单/买单），会使用最新的平均历史价格
