### ISSUE TITLE
新版本更新后，开启多开闪退

### ISSUE THREAD

**Issue by Ena-Heleneto** [qedsd/TheGuideToTheNewEden#11]
我不清楚在哪里看版本号，不过我这里有录屏可以帮助你复现问题

https://github.com/qedsd/TheGuideToTheNewEden/assets/69035266/d0e20029-6a6e-48f7-8723-affbc04725cb

**Comment by qedsd** [comment]
问题已修复，下个版本更新

**Comment by qedsd** [comment]
已在版本[v2.7.1.0](https://github.com/qedsd/TheGuideToTheNewEden/releases/tag/v2.7.1.0)修复
